import React from "react";

const PrivacyPolicy = () => (
  <div className="space-y-8">
    <div className="space-y-3">
      <h1 className="font-extrabold text-3xl md:text-4xl xl:text-5xl">Privacy Policy</h1>
      <h3 className="text-grey-800 text-sm md:text-base">Effective September 8, 2024</h3>
      <p className="font-semibold text-grey-800 md:text-base !mt-6">
        Parcel Market LLC respects your privacy and is committed to protecting your personal information. This Privacy Policy outlines how
        we collect, use, and protect the information you provide when using our website.
      </p>
    </div>

    <div className="space-y-3 md:space-y-5">
      <h1 className="font-extrabold text-xl md:text-2xl">Who are our users?</h1>
      <p className="text-grey-800 text-sm md:text-base">
        Our users are individuals seeking to estimate the value of vacant property in the United States. Vacant property is land that does
        not contain any residential structures. Whether you&apos;re a real estate agent, investor, property owner, or prospective purchaser,
        our website provides a convenient and accessible way to obtain property estimates using comparable sales figures. You must be 18
        years of age, or older, to use our website and subscribe to our services. The estimates generated by our website are a starting
        point for prospective buyers and sellers. The estimates are not appraisals and should not be relied upon in making financial
        decisions without independently verifying the value by securing a professional appraisal.
      </p>
    </div>

    <div className="space-y-3 md:space-y-5">
      <h1 className="font-extrabold text-xl md:text-2xl">What information do we collect from our users?</h1>
      <p className="text-grey-800 text-sm md:text-base flex flex-col">
        <span className="pl-6 pb-2 relative before:content-['_'] before:size-1.5 before:rounded-full before:bg-grey-800 before:absolute before:block before:top-3 before:left-2">
          Our website does not use tracking technology such as cookies or pixels. We may collect your IP address, browser type, and device
          type to help us understand how users interact with our website and improve our services.
        </span>
        Third parties, like Google, may collect data regarding your use of our website. If you choose to create an account, we store your
        name, date of birth, and country/state of origin to communicate with you, personalize your experience, and comply with legal
        requirements. If you request an estimate, we collect the parcel number, mailing address, or name of the current property owner. If
        you use the chat platform, the contents of your communications will be saved on our secure portal for a limited time period. We do
        not actively monitor chat communications, but we encourage users to email us at customerservice@parcelmarket.com if another user
        posts objectionable content to the chat. We are not a party to user negotiations, and we do not actively monitor user
        communications.
      </p>
    </div>
    <div className="space-y-3 md:space-y-5">
      <h1 className="font-extrabold text-xl md:text-2xl">How do we use your private information?</h1>
      <p className="text-grey-800 text-sm md:text-base flex flex-col">
        <span className="pl-6 pb-2 relative before:content-['_'] before:size-1.5 before:rounded-full before:bg-grey-800 before:absolute before:block before:top-3 before:left-2">
          We do not sell your private information. We use the personal information collected from users to carry out the essential functions
          of the website, improve our services, to communicate with you, and to comply with privacy regulations. We may share your personal
          information with third-party service providers, such as payment processors and analytics tools, to help us operate the website. We
          require these providers to maintain appropriate security measures to protect your data.
        </span>
      </p>
    </div>
  </div>
);

export default PrivacyPolicy;
