export enum PropertyTypesEnum {
  "Vacant Land",
  "Dairy Farm",
  "Desert",
  "Sedert Land",
  "Barren Land",
  "Farm",
  "Horticulture",
  "Agricultural",
  "Irrigation",
  "Flood Control",
  "Livestock, Animals",
  "Pasture",
  "Poultry Farm",
  "Ranch",
  "Reservoir",
  "Water Supply",
  "Rural Improved/ Non-Residential",
  "Range Land",
  "Grazing",
  "Rural",
  "Truck Crops",
  "Timberland",
  "Forest",
  "Trees",
  "Vineyard",
  "Well site",
  "Wild Life",
  "Convenience Store (7-11)",
  "Appliance Store",
  "Private Preserve,Open Space-Vacant Land",
}
